apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-webui
  namespace: hermes-agent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: hermes-webui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hermes-webui
    spec:
      volumes:
      - name: webui-data
        hostPath:
          path: /data/hermes/webui
          type: DirectoryOrCreate
      containers:
      - env:
        - name: OPENAI_API_BASE_URL
          value: http://hermes-gateway-1:8642/v1
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: api_key
              name: hermes-gateway-1-secret
        - name: WEBUI_AUTH
          value: 'true'
        - name: PORT
          value: '48080'
        - name: RAG_EMBEDDING_MODEL_AUTO_UPDATE
          value: 'False'
        volumeMounts:
        - name: webui-data
          mountPath: /app/backend/data
        image: open-webui:nl-v0.9.2-nh
        imagePullPolicy: IfNotPresent
        name: webui
        ports:
        - containerPort: 48080
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 512Mi
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

