apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hermes-ingress
  namespace: hermes-agent
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /agent1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: hermes-gateway
                port:
                  number: 8642
          - path: /agent2(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: hermes-gateway-2
                port:
                  number: 8642
          - path: /agent3(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: hermes-gateway-3
                port:
                  number: 8642
